spring.datasource.url=jdbc:postgresql://dpg-d88j9eojo6nc73cv3vn0-a.oregon-postgres.render.com:5432/futbol_db_oqeb
spring.datasource.username=futbol_db_oqeb_user
spring.datasource.password=scNd34JAIW0gLkrxj4HEQkW6h27Sy10E
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

server.port=8106